name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  Lint:
    name: Terraform Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Terraform Validate
        id: validate
        run: terraform validate
  
      - name: Run terraform fmt check
        id: fmt
        run: terraform fmt -check -diff -recursive
  
  Dev:
    name: Dev Deployment
    runs-on: ubuntu-20.04
    environment:
      name: Development
    needs: Lint
    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::847175655404:role/TerraformUser
          role-session-name: InfraDeployOnMerge

      - name: Initialize Terraform
        id: init
        run: |
          rm -rf .terraform.*
          terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: |
          ENV=Dev make plan \
          && terraform show Dev.plan
        continue-on-error: false

  Prod:
    name: Prod Deployment
    runs-on: ubuntu-20.04
    needs: Lint
    environment:
      name: Production
    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::847175655404:role/TerraformUser
          role-session-name: InfraDeployOnMerge

      - name: Initialize Terraform
        id: init
        run: |
          rm -rf .terraform.*
          terraform init -input=false

      - name: Terraform Plan - Production
        id: plan
        run: |
          ENV=Prod make plan \
          && terraform show Prod.plan
        continue-on-error: false

      # - name: Terraform Deploy - Production
      #   id: deploy
      #   run: |
      #     ENV=Prod make apply \
      #     && terraform show Prod.plan
      #   continue-on-error: false